# Generated by Django 3.2 on 2021-04-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
